

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dropboxproject
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  dropbox-app:
    build: .
    container_name: dropbox-container
    ports:
      - "8080:8080"
    environment:
      # MySQL Bağlantı Bilgileri
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/dropboxproject?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: dbpassword
      
      # Email Bilgileri
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: javadosyapaylasimi@gmail.com
      SPRING_MAIL_PASSWORD: X5j13$#eCM1cG@Kdc
      
      # Spring Profil Ayarı
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql-db:
        condition: service_healthy

volumes:
  mysql_data: